### ISSUE TITLE
about left join

### ISSUE THREAD

**Issue by liushaoCode** [khennig/jpql-querybuilder#1]
Can I support left join?
 Can I get your contact information?

**Comment by khennig** [comment]
Basically yes, as part of the FROM Clause. There is no special API support, intentionally.
`// setup`
`QueryBuilder builder = new QueryBuilder();`
`builder.select.add("field-1");`
`builder.from.add("column-1 LEFT JOIN column-2");`
`builder.where.add("field-1=1");`
`// test, assert`
`assertThat(builder.render()).isEqualTo(`
`"SELECT field-1 FROM column-1 LEFT JOIN column-2 WHERE (field-1=1)");`

**Comment by liushaoCode** [comment]
can you upgrade your API?
I hope it can support under result.
QueryBuilder builder = new QueryBuilder();
builder.leftJoinTable(ObjectTable);

**Comment by khennig** [comment]
I'm not sure if it makes sense as A & B in "A LEFT JOIN B" are in a way tied together.
The intention of the jpql-querybuilder is to add "self contained" parts to the whole statement building it bit by bit, see "A dynamic query" in README.md.
Do you have a sample, a statement, to show why you want to split the construction of "A LEFT JOIN B"?
Your API suggestion, "builder.leftJoinTable(ObjectTable);", how to build "A LEFT JOIN B", how do you want to relate A and B as there could be more items in the FROM Clause (FROM A JOIN B JOIN C ...)?
Sorry for closing the issue too fast.
